### ISSUE TITLE
MP5 not taken into consideration for MP5

### ISSUE THREAD

**Issue by Xilmi** [getov/CharacterStatsClassic#10]
Mana-regen seems to ignore whatever you get from MP5 items.

**Comment by getov** [comment]
It's a bug on Blizzard's side. Nothing I can do about it.
https://us.forums.blizzard.com/en/wow/t/buff-cap-and-hidden-auras/297178/63

**Comment by getov** [comment]
I've applied a workaround and it detects mp5 from items only (no buffs)
