### ISSUE TITLE
Warrior's Defence still not showing right.

### ISSUE THREAD

**Issue by Ardash** [getov/CharacterStatsClassic#11]
subject

**Comment by Ardash** [comment]
![image](https://user-images.githubusercontent.com/4602853/66855450-e7cd6100-ef8b-11e9-8b06-44024b3497ed.png)

**Comment by getov** [comment]
Hello, I've just updated the addon (version 2.4) - If it is still not updated on Curse, you can get it from github.

Hopefully it should work now. I've added support for custom localization. Under Localization\Localization_ru.lua , can you check if I translated the "Weapon Skills" string correctly?
If it works it should be fine.

**Comment by Ardash** [comment]
Thanks. It works correctly now.
