### ISSUE TITLE
Random lua error when logging in

### ISSUE THREAD

**Issue by thevipe** [getov/CharacterStatsClassic#13]
Date: 2019-10-13 10:46:24
ID: 1
Error occured in: Global
Count: 3
Message: ...CharacterStatsClassic\CharacterStatsClassicUtils.lua line 97:
   attempt to index local 'stats' (a nil value)
Debug:
   [C]: ?
   ...CharacterStatsClassic\CharacterStatsClassicUtils.lua:97:
      ...CharacterStatsClassic\CharacterStatsClassicUtils.lua:89
   ...CharacterStatsClassic\CharacterStatsClassicUtils.lua:697: CSC_PaperDollFrame_SetManaRegen()
   ...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:97: SetCharacterStats()
   ...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:120: UpdateStats()
   ...\CharacterStatsClassic\CharacterStatsClassicCore.lua:22:
      ...\CharacterStatsClassic\CharacterStatsClassicCore.lua:21
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AdvancedInterfaceOptions, v1.3.3
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasDungeonLocs, vv1.45.00.11302.01
  AtlasLootClassic, vv1.3.0
  AtlasLootClassicData, vv1.3.0
  AtlasLootClassicDungeonsAndRaids, vv1.3.0
  AtlasQuest, v4.11.54
  Auctionator, v8.1.0
  BagBrother, v
  Bagnon, v8.2.16
  BiSTracker, v1.4 
  CharacterStatsClassic, v2.2
  ClassicAuraDurations, v
  Clique, vv11302-1.0.0
  CrossGambling, v8.2.0
  DBMCore, v1.13.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.4
  Details, v
  DetailsTinyThreat, v
  DismountMe, v1.5
  ElvUI, v1.14
  GatherMate2, v1.45.5-1-gab6216a
  Grail, v101
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v27178
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v29297
  GrailReputationsclassic, v007
  GTFO, v4.50.1
  GuildRosterManager, v1.76
  LeatrixPlus, v1.13.34
  LunaUnitFrames, v3038
  Mapster, v1.8.5-1-g3e96752
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  Necrosis, v5.0
  OmniCC, v8.2.5
  Prat30, v3.7.36-2-g374a268
  Prat30Libraries, v
  Questie, v4.2.1 0 0f28ee6
  RollTrackerClassic, v1.50
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SmartBuff, v1.13.2d
  Stubby, v8.2.6376 (SwimmingSeadragon)
  Thaliz, v0.2.2
  TitanClassic, v1.1.1.11302
  TitanClassicAmmo, v1.1.1.11302
  TitanClassicBag, v1.1.1.11302
  TitanClassicClock, v1.1.1.11302
  TitanClassicGold, v1.1.1.11302
  TitanClassicLocation, v1.1.1.11302
  TitanClassicLootType, v1.1.1.11302
  TitanClassicPerformance, v1.1.1.11302
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.1.11302
  TitanClassicVolume, v1.1.1.11302
  TitanClassicXP, v1.1.1.11302
  TomTom, vv11302-1.0.7
  TrinketMenu, v7.3.2
  Wholly, v072
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=72a)

**Comment by getov** [comment]
Thank you, I've applied a hotfix.
