### ISSUE TITLE
Rogue + [Royal Seal of Eldre'Thalas] = bugged hit rating

### ISSUE THREAD

**Issue by Nillx** [getov/CharacterStatsClassic#15]
Found a weird bug when equipping the rogue DM hit rating trinket ([Royal Seal of Eldre'Thalas]).

How to reproduce it:

My hit rating is 6%
- When i equip [Royal Seal of Eldre'Thalas] my hit rating doesnt change (i should have 8% when wearing the trinket)
- When i take off [Royal Seal of Eldre'Thalas] my hit rating goes up to 8% (with an empty trinket slot)
- When i equip another trinket without hit rating, my hit goes down to 6% again

Screenshots example: https://imgur.com/a/OCo0jTi

**Comment by getov** [comment]
It sounds like the following bug on Blizzard's end:
https://us.forums.blizzard.com/en/wow/t/buff-cap-and-hidden-auras/297178/2

They say that they've applied a fix for the "passive hidden" auras, but nothing about the hit problem.

**Comment by Nillx** [comment]
Yea exactly the same issue

**Comment by Nillx** [comment]
мерси за полезния аддон :)
