### ISSUE TITLE
Defense only showing base defense (not bonuses)

### ISSUE THREAD

**Issue by Xatrith** [getov/CharacterStatsClassic#16]
Hello,

As someone commented on curse, the defense part is not counting any modifier. I use the french client and i don't know since when it does that.

Anyway, great add on. I really like it :)

**Comment by getov** [comment]
in the Localization folder there are different files for the languages. Find the one that ends with _fr and open it. When you translate the "Weapon Skills" string (the one that shows up when you press "K" in game), it should work. 
Also send me the string so I can update it with the next release :)

**Comment by Xatrith** [comment]
Modification done, but it had no effet. Tried setting the game in english and the function works fine in this language.
Replaced : Weapon Skills by Compétences d'armes
Also tried replacing : "DEFENSE" by "Défense" or "DÉFENSE".
Prevented the window from opening.

**Comment by getov** [comment]
Just tested and it looks like the blizzard string is in this format : Compétences d’armes
note that  '  and  ’  are different symbols and they use the second one.... Try it and it should work. It's really hard with all those different punctuations :P

**Comment by Xatrith** [comment]
Yes, worked perfectly. Thx :)


[Localization_fr.zip](https://github.com/getov/CharacterStatsClassic/files/3776562/Localization_fr.zip)

**Comment by getov** [comment]
Updated on Curse.
