### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by Finrodi** [getov/CharacterStatsClassic#17]
> 1x [ADDON_ACTION_BLOCKED] AddOn 'CharacterStatsClassic' tried to call the protected function 'PaperDollFrame:Show()'.
> !BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
> [C]: in function `Show'
> FrameXML\CharacterFrame.lua:40: in function `CharacterFrame_ShowSubFrame'
> ...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:203: in function `ToggleCharacter'
> [string "TOGGLECHARACTER0"]:1: in function <[string "TOGGLECHARACTER0"]:1>
> 
> Locals:
> InCombatSkipped

Also think that it sometimes block me from opening my character panel in combat..

**Comment by Finrodi** [comment]
> 1x [ADDON_ACTION_BLOCKED] AddOn 'CharacterStatsClassic' tried to call the protected function 'PaperDollFrame:Hide()'.
> !BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
> [C]: in function `Hide'
> FrameXML\CharacterFrame.lua:35: in function `CharacterFrame_ShowSubFrame'
> ...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:203: in function `ToggleCharacter'
> [string "TOGGLECHARACTER1"]:1: in function <[string "TOGGLECHARACTER1"]:1>
> 
> Locals:
> InCombatSkipped

**Comment by getov** [comment]
Should be resolved with the latest update (2.6)
