### ISSUE TITLE
Weapon skill formulas are wrong

### ISSUE THREAD

**Issue by magey** [getov/CharacterStatsClassic#19]
There are a few issues with the implementation of weapon skill formulas. 

Weapon skill doesn't give you bonus hit chance; it **reduces your miss chance** and, depending on the skill/defense delta, makes you ignore the 1% penalty to +hit from gear/talents/buffs vs. +3 mobs.  This is an important distinction as the reduced miss chance varies by the skill/defense delta and target type (NPC vs. player) and is used as the base miss chance to calculate the dual-wield miss penalty. It also means you can't just add the weapon skill difference to the hit bonus.

Additionally, the formulas used in the addon to calculate miss chance are wrong; see https://github.com/magey/classic-warrior/wiki/Attack-table for full details.

My suggestion is to remove the current functionality and add miss chances vs. various types of mobs and players in the tooltip that shows when you hover over 'Hit Chance'. You should also clarify that +hit bonus from gear/talents/buffs doesn't actually increase your chance to hit - what it does is reduce your chance to miss; again, an important distinction as it basically converts Miss entries in the attack table to Hit entries. You can optionally also include the dual-wield miss chance. Example tooltip could be something like this:

```
+Hit Chance: 6%
Reduces your chance to miss.

Miss chance vs.
    Level 60 NPC: xx.x% (xx.x% dual wield)
    Level 60 Player: xx.x% (xx.x% dual wield)
    Level 63 NPC/Boss: xx.x% (xx.x% dual wield)
```

If you need any clarifications or assistance feel free to contact me on the Fight Club discord.

**Comment by getov** [comment]
"Weapon skill doesn't give you bonus hit chance; it reduces your miss chance"

This is technically the same - reducing your chance to miss increases your chance to hit.

The formulas are not wrong. I've used another source for them since at the time of implementing this, the github source you provided was not very complete and they said they needed more testing.

I might look into it again when I have time.

**Comment by getov** [comment]
And yes, I take into consideration the skill/defense delta. I just used a different table.

Thanks for the feedback, again when I have more time I will try to improve it :)

**Comment by magey** [comment]
> This is technically the same - reducing your chance to miss increases your chance to hit.

It's not the same because your dual-wield miss chance is derived from your normal miss chance. In addition, you can't just stay that weapon skill gives you bonus hit; it differs depending on what you're attacking. If it gave you bonus hit you would get the same bonus hit vs. all targets. What it does is modify your base miss chance.

> The formulas are not wrong. I've used another source for them since at the time of implementing this, the github source you provided was not very complete and they said they needed more testing.

Yes they are wrong. And the wiki I linked is the only source with accurate and reliable attack table information for Classic WoW, verified to very low error margins on the beta and now verified through WCL logs. Any other source you find on the internet was either copied from that wiki, is an outdated vanilla source, is an irrelevant post-vanilla source (TBC/WotLK/etc.) or is a wrong pserver source.

The correct way to calculate your miss chance:

```
delta = target.defense - player.weapon_skill
hit_chance = player.hit_chance

if (target.is_npc)
{
	if (delta > 10)
	{
		if (hit_chance >= 1%)
		{
			hit_chance = hit_chance - 1%
		}
		
		miss_chance = 5% + delta * 0.2%
	}
	else
	{
		miss_chance = 5% + delta * 0.1%
	}
}
else
{
	miss_chance = 5% + delta * 0.04%
}


miss_chance = miss_chance - hit_chance
miss_chance = clamp(miss_chance, 0%, 100%)
```

**Comment by getov** [comment]
Reopening this. I like the idea of displaying additional info as a tooltip. Also gonna fix the calculations.
It will probably be the next bigger thing I'm gonna work on.

**Comment by getov** [comment]
I've updated the addon with a new tooltip showing the miss chances. For players and NPCs I use 300 as a base value for defense, since there is no good way to show it dynamically depending on the target's defense.

Just to make sure I understand it right - The formula for the dual wield miss chance is for the white hits?
