### ISSUE TITLE
Are PRs welcome?

### ISSUE THREAD

**Issue by Masgalor** [getov/CharacterStatsClassic#2]
Hey.
I've stumbled upon your addon what does exactly what I want, in a lightweight way.

However, there are some problems with classic clients when localization differs from english.
I run the german client, where different texts overlap each other.
Also the usage of localized strings is kind of inconsistent.

Do you mind me opening some PRs to cover these issues?

**Comment by getov** [comment]
Sure you can do PRs !
I will definitely need help with localization. 
I was planning to never implement it since I don't have the time, but I will include any working localization made by others.

**Comment by Masgalor** [comment]
Good to hear.

I have absolutely zero experience with wow addon development.
We will see if I can provide some useful code. ;)
