### ISSUE TITLE
Feral weapon skill calculation in miss chance

### ISSUE THREAD

**Issue by byeuji** [getov/CharacterStatsClassic#22]
It looks like the miss chance calculation does not take into consideration whether or not I am in forms.

When a feral druid is in forms, all weapon skills are considered maxed (level * 5), regardless of what their *actual* weapon skills are. The reason for this is that they aren't technically holding any weapons in forms, and their skill with feral attacking is always maxed (like languages).

I noticed that in equipping the Big Iron Fishing Pole, which is a weapon-type Fishing Pole (similarly always considered maxed), the miss formula appears to work. So maybe you can add the feral forms exception to this when class is druid and form is not form:0.

**Comment by Masgalor** [comment]
I guess its not that complicated to write an exception using `UnitClass("unit")` and `GetShapeshiftForm(flag)`.

@getov do you mind if I open a PR for this?

**Comment by getov** [comment]
Sure you can open! I will probably have time by the end of the week to look through these.

**Comment by Masgalor** [comment]
PR is up.
#25
