### ISSUE TITLE
Lua Error 1

### ISSUE THREAD

**Issue by Altoholic** [getov/CharacterStatsClassic#30]
I got this at every login:

Message: ...CharacterStatsClassic\CharacterStatsClassicUtils.lua:303: Division by zero
Time: Sat Feb 29 19:36:50 2020
Count: 1
Stack: ...CharacterStatsClassic\CharacterStatsClassicUtils.lua:303: Division by zero
...CharacterStatsClassic\CharacterStatsClassicUtils.lua:303: in function `CSC_PaperDollFrame_SetDamage'
...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:84: in function `SetCharacterStats'
...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:123: in function `UpdateStats'
...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:118: in function `CreateMenu'
...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:237: in function <...ns\CharacterStatsClassic\CharacterStatsClassicUI.lua:221>

Locals: statFrame = <unnamed> {
 0 = <userdata>
 OnEnterCallback = <function> defined *:OnEnter:1
 Label = <unnamed> {
 }
 Value = <unnamed> {
 }
 Background = <unnamed> {
 }
}
unit = "player"
category = "Melee"
speed = 0
offhandSpeed = nil
minDamage = 0
maxDamage = 0
minOffHandDamage = 0
maxOffHandDamage = 0
physicalBonusPos = 0
physicalBonusNeg = 0
percent = 0
displayMin = 1
displayMax = 1
(*temporary) = 0
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Division by zero"
CSC_PaperDollFrame_SetLabelAndText = <function> defined @Interface\AddOns\CharacterStatsClassic\CharacterStatsClassicUtils.lua:59
CSC_GetAppropriateAttackSpeed = <function> defined @Interface\AddOns\CharacterStatsClassic\CharacterStatsClassicUtils.lua:36
CSC_GetAppropriateDamage = <function> defined @Interface\AddOns\CharacterStatsClassic\CharacterStatsClassicUtils.lua:27
CSC_GetAppropriateAttackRaiting = <function> defined @Interface\AddOns\CharacterStatsClassic\CharacterStatsClassicUtils.lua:45

**Comment by getov** [comment]
Fixed in 822ec9ed49f81af2c5de03ba06064d94c66be3c5
