### ISSUE TITLE
Final fix for blockvalue detection

### ISSUE THREAD

**Issue by Masgalor** [getov/CharacterStatsClassic#32]
Hey @getov, after testing your latest update I have to tell you that the blockvalue is still not correct.

However, its easy to fix, so easy that I will describe it here instead of opening a PR.

1. If a might item is detected the counter is increased at each line of the tooltip a `break;` after line 772 would prevent this.

2. The bonus is only added if there are exactly 3 pieces of might present maybe a `>=` would do better in line 801.

Im glad you finally got this working, thanks.

**Comment by getov** [comment]
Thanks for the catch, yeah, some silly mistakes.
However I am not sure if the WoW's version of Lua, which is 5.1 supports "break" statements.

**Comment by Masgalor** [comment]
I can confirm its finally fixed with 3.3.3.
