### ISSUE TITLE
[request] crit cap

### ISSUE THREAD

**Issue by Altoholic** [getov/CharacterStatsClassic#33]
It could be a great addition, in the melee tab, to have crit cap.
Maybe with a color (white or green if not capped, red otherwise).

**Comment by getov** [comment]
I will be checking out some sources and implement it in a future update.

**Comment by Altoholic** [comment]
If that can help, a guy used that formula to make some WA (https://wago.io/LC8_MCdQN and https://wago.io/KxMHui-TF):
critCap = 100 - missChance - dodgeChance - glancingChance + 4.8 + (extraWeaponSkill * 0.04)
Also, the classic rogue discord use that sheet: https://docs.google.com/spreadsheets/d/1NWKnSmYseruEUb06wOYbWHS6IxriHNd7E2fkBRBXxLY/copy

**Comment by getov** [comment]
Implemented as a tooltip in the latest release
