### ISSUE TITLE
Holy crit from bene not counted

### ISSUE THREAD

**Issue by ashtaar007** [getov/CharacterStatsClassic#34]
Version: 3.4.1
![bene](https://user-images.githubusercontent.com/6677165/79664126-10c0ef80-8183-11ea-8f79-2f619c613c4f.png)
![with bene](https://user-images.githubusercontent.com/6677165/79664147-13234980-8183-11ea-91ac-ff515ff95850.png)
![without bene](https://user-images.githubusercontent.com/6677165/79664171-14547680-8183-11ea-937f-a08827913f16.png)

**Comment by getov** [comment]
Fixed in 7591dfe3f1fc16962f7c7e87f78cc7a8c535ffde
