### ISSUE TITLE
Mp5 from Prophetic Aura ZG enchant not counted

### ISSUE THREAD

**Issue by ashtaar007** [getov/CharacterStatsClassic#35]
Version: 3.4.1
![halo  of transcendence](https://user-images.githubusercontent.com/6677165/79664910-4a91f600-8183-11ea-9a37-223fa0a9913c.png)
![with helm](https://user-images.githubusercontent.com/6677165/79664932-4bc32300-8183-11ea-9150-7ed04331dc7d.png)
![without helm](https://user-images.githubusercontent.com/6677165/79664955-4d8ce680-8183-11ea-8b35-e35ab97f3d50.png)

**Comment by getov** [comment]
Fixed in 3.6.3
