### ISSUE TITLE
[Improvement] Missing Warlock Crit Talent

### ISSUE THREAD

**Issue by stefan0uh** [getov/CharacterStatsClassic#37]
Maybe I missed it, but it looks like the Warlock Destruction crit talent is missing in the crit calculation.

https://classic.wowhead.com/spell=18130/devastation

**Comment by getov** [comment]
Yep, it's missing. I haven't thought of a good way to present the spells' specific stats like Destruction. Is "destruction" scrit different from "shadow" crit or is it the same?

**Comment by stefan0uh** [comment]
It is the same.

All spells with a cast time are destruction (and do damage).
All spells with no cast time are affliction.

So devastation is shadow crit, cause dots can not crit.

**Comment by getov** [comment]
In that case it shouldn't be too hard to add it into the calculation for shadow crit.

**Comment by getov** [comment]
Added in the latest release (3.5.2)
