### ISSUE TITLE
Holy Priest Issue

### ISSUE THREAD

**Issue by AnonymousPerson12345** [getov/CharacterStatsClassic#44]
Nothing too fancy - the addon is just not adding the +5% holy crit from the holy talent tree.

**Comment by getov** [comment]
Put your gear and enchants here: https://classic.wowhead.com/gear-planner/priest
Then compare the numbers to your in-game values.
If there is still a problem, I will look into it

**Comment by AnonymousPerson12345** [comment]
Well, you can actually tell that it's not accounting for holy crit by just looking at the CharacterStats interface in-game. It lists all of my spell crits (holy, shadow, fire, etc.) as the exact same -- they are all at 8.15%. So it is clear that it is not bumping up the holy crit by the 5% from the talent.
