### ISSUE TITLE
Values from ZG enchants

### ISSUE THREAD

**Issue by Masgalor** [getov/CharacterStatsClassic#46]
Values from ZG enchants are missing on stats that are not retrieved using the api but calculated by ourself.

Cases Im aware are:
 - Warrior Blockvalue (if api is disabled)
 - Priest MP5
   #35 #45 

Since these enchants will always be relevant I would like to get this fixed.
I will try to come up with something to detect the enchant and add those values.
Assuming your approval.

**Comment by getov** [comment]
I will have a look at the ZG enchants.

**Comment by getov** [comment]
Fixed in 3.6.3
