### ISSUE TITLE
Holy Paladin spell crit chance

### ISSUE THREAD

**Issue by Dropbooster** [getov/CharacterStatsClassic#47]
![image](https://user-images.githubusercontent.com/71389658/93343374-16595900-f839-11ea-8bed-64494fcc9e22.png)
![image](https://user-images.githubusercontent.com/71389658/93343413-207b5780-f839-11ea-85b1-02e2daeccd24.png)

Holy Palas have additional 5% spell crit chance by talent Holy Power, but that not shown in addon.

**Comment by getov** [comment]
It is. For some reason Holy Power gives +5 crit to all spell schools.

**Comment by Dropbooster** [comment]
So then spell crit chance shown incorrect. Logs says about 5% deviation in 1000 casts selection. Also another stats addon show correct info.
![image](https://user-images.githubusercontent.com/71389658/93467907-e6708b00-f8f6-11ea-9993-759aa631ce79.png)
