### ISSUE TITLE
Defense Tooltip isn't based on bonus defense.

### ISSUE THREAD

**Issue by GMPeka** [getov/CharacterStatsClassic#48]
![image](https://user-images.githubusercontent.com/13225060/93666906-d7661600-fa79-11ea-9f7c-d4ce17e91acd.png)

Currently your addon is showing bonus mitigation calculated using total defence skill (324\*0.04), rather than bonus defense skill above your level ((324-level\*5)\*0.04). So in the above screenshot it should be showing 0.96%, rather than 12.96%.

**Comment by getov** [comment]
It was always intended to show it based on the total defense skill. Is there any reason you want it displayed otherwise ?

**Comment by GMPeka** [comment]
It just more logical for it to show the bonus Dodge, parry, etc amount against a mob your own level, since every other stat in the game is displayed as if you was facing a target your own level, like crit chance or armor, etc. 300 defence at level 60 is baseline and doesn't count towards your mitigation against a target your own level.

![image](https://user-images.githubusercontent.com/13225060/93687996-6c88ff00-faba-11ea-8885-718bd12382ba.png)

As an example for how other stats are show, in the above screenshot, my chance to Parry is 5.28%, that is because against a mob your own level you have a baseline 5% parry chance, plus 0.04% from each point defence above 300. So it'd make sense if in the Defense tooltip showed 0.28% to match that.

They way you have bonus mitigation shown currently isn't mathematically wrong, it's just irrelevant and doesn't fit in with how other stats are shown, since every other stat is shown for if you was facing a target you own level, not a level 0.

**Comment by Masgalor** [comment]
@getov since this issue is still up I guess you are not against those chages?

I have to agree with @GMPeka that the value presented here is not really informative.
Maybe we should make it the way we display the chance to hit an enemy.

I will give it a try, assuming your approval.

**Comment by getov** [comment]
I agree with the changes, haven't had much time to do anything with the addon these days. If you already have any ideas in mind, you are free to implement them @Masgalor
