### ISSUE TITLE
[Feature]Add Elemental Shaman crit/hit from talents

### ISSUE THREAD

**Issue by stefan0uh** [getov/CharacterStatsClassic#49]
Hi, can you add the shaman talents bonus for crit and hit.

### Crit 
- [Call of Thunder](https://classic.wowhead.com/spell=16041) is only applied to the lightning spells.
- [Tidal Mastery](https://classic.wowhead.com/spell=16194) affects healing/nature and lightning spells

### Hit
- [Nature's Guidance](https://classic.wowhead.com/spell=16180) counts for melee and spell hit

### Spell School's
- **Lightning** spells are Lightning Bolt and Chain Lightning
- **Nature** spells are all Shaman spells except Frost/Fire/Shadow/Holy ...

**Comment by getov** [comment]
Heya, I've added this to the latest version (3.6.4)

**Comment by gpexio** [comment]
Probably related to this - after the last update, now I read 12% hit chance with my regular shaman PVE 9% hit set. I think Nature's Guidance was already being counted towards hit chance.

**Comment by getov** [comment]
So you have only +6 hit from items and Nature's Guidance is double counted **only** for melee and not ranged?

**Comment by gpexio** [comment]
> So you have only +6 hit from items and Nature's Guidance is double counted **only** for melee and not ranged?

This is my gear, 6% melee hit and 0% spell hit from items and 3% from Nature's Guidance
https://sixtyupgrades.com/set/6AtaWi9pzK6sjN6ugYqf4F

Addons shows 12% melee hit
![Melee](https://user-images.githubusercontent.com/18090037/95688337-d1db9600-0c09-11eb-9011-afbbd9679374.png)

and 6% spell hit
![caster](https://user-images.githubusercontent.com/18090037/95688360-f9caf980-0c09-11eb-9a61-7510421ae306.png)

**Comment by getov** [comment]
Alright then, thank you, It seems like it is adding it by default and I will revert my manual work!

**Comment by gpexio** [comment]
no problem m8. thanks for your work
