### ISSUE TITLE
Range Attack Speed 

### ISSUE THREAD

**Issue by lordkj** [getov/CharacterStatsClassic#5]
Hello 

Range Attack Speed is not correct it's the same as melee attack speed and don`t take value of the Range weapon.
![WoWScrnShot_091019_151443](https://user-images.githubusercontent.com/5272572/64613209-4aa46900-d3de-11e9-9f30-94f9d47b4096.jpg)
![WoWScrnShot_091019_151448](https://user-images.githubusercontent.com/5272572/64613211-4aa46900-d3de-11e9-82fd-64b3728f2ab0.jpg)
![WoWScrnShot_091019_151808](https://user-images.githubusercontent.com/5272572/64613212-4aa46900-d3de-11e9-8fa5-c990ef92b707.jpg)
![WoWScrnShot_091019_151811](https://user-images.githubusercontent.com/5272572/64613213-4aa46900-d3de-11e9-8f4a-ce4eede03953.jpg)

**Comment by getov** [comment]
Thank you for the feedback!
I've fixed it in the latest release (1.8)
Can you update and confirm that it is working correctly ?

**Comment by lordkj** [comment]
Thank you very much it's working Great !!! And Thank you for the good work.
