### ISSUE TITLE
[Bug] Priest spritiual healing has no effect on +heal, should be removed from calculation

### ISSUE THREAD

**Issue by sl4ker** [getov/CharacterStatsClassic#50]
## Observation
Since the last commit, spiritual healing is added to the total +spell healing in the character sheet calculation for priests

## Expectation
Spiritual healing should have no influence on +spell healing

## Explanation
Spiritual healing only increases base heal of healing spells. All +heal bonus from equip is ignored and irrelevant for this talent. This can be easily tested by using any healing spell (renew works best) and calculating the added +heal to the base spell values. The current 1.1 modifier to spell healing due to spiritual healing in commit eb60fe09a8c651a8f3f9e7a65474a224e1d9b8ca is wrong.

## Example
![image](https://user-images.githubusercontent.com/1568672/95675935-15f37a00-0bbb-11eb-9cc1-b0295f4c4f29.png)
Spiritual healing is skilled 5/5 and no improved renew
![image](https://user-images.githubusercontent.com/1568672/95675939-20ae0f00-0bbb-11eb-9179-686f5df293df.png)
Renew Rank 3 should heal 195 after all talents (https://classic.wowhead.com/spell=6075/renew base spell only heals 175)
![image](https://user-images.githubusercontent.com/1568672/95676021-75518a00-0bbb-11eb-9d85-22fe7e735d3a.png)
Each renew tick of rank 3 ticks for 244, so 1220 in total
![image](https://user-images.githubusercontent.com/1568672/95675927-08d68b00-0bbb-11eb-9875-b67ac7a2a0be.png)
This is the +heal value shown with the most recent commit.

If we subtract the base heal of 195 from the total renew (100% coefficient), we get 1025 +heal. This is the original, correct value. The new calculation since commit eb60fe09a8c651a8f3f9e7a65474a224e1d9b8ca multiplies this value by 1.1 and arrives at a wrong value of 1129.7 (which is also wrong due to rounding errors, but this is another floating point problem that classic has everywhere).

Character planner link with equip (without spirit buff, which would add ~10 +heal for a total of 1026) https://classic.wowhead.com/gear-planner/priest/undead/AjwQUAIxEwUAHyBRUQMDAAVf8IFCGV5nAlQDg02BX2SFQhs2dQZNgodLuV5niEvtNkKJQh5c-opCGGH3C0rEDFLaDUtYDkvDD0hOkFOiWN4RS3ASVSk

**Comment by getov** [comment]
Thanks for the feedback, I got it wrong and I will revert this in the next version!
