### ISSUE TITLE
MP5 from Enchant Bracer - Mana Regeneration not counted

### ISSUE THREAD

**Issue by Laumesis** [getov/CharacterStatsClassic#55]
MP5 from [Enchant Bracer - Mana Regeneration](https://classic.wowhead.com/spell=23801/enchant-bracer-mana-regeneration) is not added to Mana Regen. Neither to MP5 from gear or other mana regen values.

Gear in Gear Planner:
https://classic.wowhead.com/gear-planner/mage/gnome/AjwAiUGfXPk

Gear:
![Gear](https://i.imgur.com/KEYMHea.png)

MP5 stats:
![MP5](https://i.imgur.com/MrFjzRZ.png)

**Comment by getov** [comment]
Fixed in 5061ec38136fafcbe0c9ae749efe0f2b1f65b214
A version will be released next week.
