### ISSUE TITLE
Feature request: Show one decimal in Mana Regen (While Not Casting)

### ISSUE THREAD

**Issue by Laumesis** [getov/CharacterStatsClassic#56]
Addon's code floors mp5 gained from spirit. Please remove flooring and let already existing number formating show one decimal.
Actual regen in the game does not do flooring for mana gains from spirit.

**Comment by getov** [comment]
I've fixed that. You can test it by getting the addon from here: https://github.com/getov/CharacterStatsClassic/releases
Or wait until next week when I upload it to Curse.
