### ISSUE TITLE
Request: Show +damage versus Undead

### ISSUE THREAD

**Issue by mtk5132** [getov/CharacterStatsClassic#57]
Would it be possible to include an option to show damage done versus Undead mobs?

With the inclusion of items like https://classic.wowhead.com/item=23207/mark-of-the-champion and mages running the Undead Cleansing Set (https://classic.wowhead.com/gear-planner/mage/gnome/AjwAgVNjXmQCVGiDS6pfZYVaLU45BkrAh1SsXmSIU2A2QolaM04oilosYfYLVM0MSssNWqcOS7MPTZEQUxkSLeQ) I think it would make a great addition if the +damage would be visible on the character pane.

This could either be on its own, or included in the total Spell Power (and showing as separate in tooltip).

**Comment by getov** [comment]
I've added this as an option. In the addon's settings you can toggle it on or off (it is ON by default).
You can test it by manually downloading from here: https://github.com/getov/CharacterStatsClassic/releases
I will be uploading it to Curse next week.
