### ISSUE TITLE
Priest Holy Spec talent not reflected in pane

### ISSUE THREAD

**Issue by mabeauchamp** [getov/CharacterStatsClassic#6]
Holy crit chance should be 4% higher based on my talents.

![image](https://user-images.githubusercontent.com/1746080/64622342-30a26080-d3b5-11e9-89ba-9e22b9d098c5.png)

**Comment by getov** [comment]
Thanks for the report!
It should be fixed in the latest release (1.8) but I cannot test it.
Can you confirm if it's working when you update?

**Comment by mabeauchamp** [comment]
For sure!
