### ISSUE TITLE
Mp5 on Resilience of the Scourge Enchant Issue

### ISSUE THREAD

**Issue by lopez9545** [getov/CharacterStatsClassic#61]
![WoWScrnShot_011021_225352](https://user-images.githubusercontent.com/77259663/104148241-1a385a80-5397-11eb-92a4-732b5ea990c3.jpg)
![WoWScrnShot_011021_225359](https://user-images.githubusercontent.com/77259663/104148243-1ad0f100-5397-11eb-80c1-bc9045b69ef4.jpg)
![WoWScrnShot_011021_225411](https://user-images.githubusercontent.com/77259663/104148245-1ad0f100-5397-11eb-9c66-db4c67611e3b.jpg)

5 Mp5 on Resilience of the Scourge Enchant on shoulders is not showing up

**Comment by getov** [comment]
Fixed in v3.7.3 (6e31c81266a675c234e1eb95d3ed465b58e64d22)
