### ISSUE TITLE
Mp5 on mana oil not calculated

### ISSUE THREAD

**Issue by Frightenz** [getov/CharacterStatsClassic#63]
Brilliant mana oil's 12mp5 does not display in character sheet once applied.

First screen shot shows 150mp5 with oil and weapon equipped

![Screen Shot 2021-01-18 at 9 06 20 PM](https://user-images.githubusercontent.com/77651277/104978942-19c04500-59d1-11eb-944f-56a37e5bdfe7.png)

Removing weapon removes 15mp5 from the weapon but not the 12mp5 from oil

![Screen Shot 2021-01-18 at 9 06 32 PM](https://user-images.githubusercontent.com/77651277/104978974-33618c80-59d1-11eb-9965-4a328f6dd4ec.png)

Mp5 was not added when oil was applied but forgot to get before/after screenshots

**Comment by getov** [comment]
Fixed in v3.7.3 (6e31c81266a675c234e1eb95d3ed465b58e64d22)
