### ISSUE TITLE
Characters stats bugged

### ISSUE THREAD

**Issue by Jansevalentin** [getov/CharacterStatsClassic#66]
![image](https://user-images.githubusercontent.com/83599581/116899020-5d188980-ac37-11eb-99ea-cc20aa711bc8.png)

as showed on the SC, the addon is bugged, it is both showing add, and not removing std, stat shower

**Comment by getov** [comment]
It might be another addon causing incompatibility. Try turning off all the other addons and see if the same bug occurs.

**Comment by Jansevalentin** [comment]
it works if i turn all others off, brb finding out which addons makes the bug, will take a few hours will all my addons

**Comment by Jansevalentin** [comment]
it is leatrix plus causing the issue
u can close this bug

**Comment by getov** [comment]
Thanks for the input! I will see if a fix can be made. I also use LTP but I don't have the issue. Will get the latest version and check again

**Comment by Jansevalentin** [comment]
i downloaded, a old version of LTP, and it started working again

**Comment by getov** [comment]
I've send a pull request to LTP in order to make it work. It is now up to LTP to implement it.
