### ISSUE TITLE
CharacterStatsClassic overlay mixed with blizzard orginal stats please help

### ISSUE THREAD

**Issue by alishiarin** [getov/CharacterStatsClassic#67]
as tittle described, the original blizzard status numbers are overlayed with the addon, showing mixed numbers on the character panel. please help on how to fix it, tried deletion and reinstall, restart the game. etc. still did not work. thank you!
![IMG_7532](https://user-images.githubusercontent.com/83849668/117521973-800faa00-af65-11eb-93fa-833e4b6e37e9.JPG)

**Comment by getov** [comment]
Make sure to download the latest version of CharacterStatsClassic and the latest alpha of Leatrix Plus - https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all 
There was an incompatibility issue which is now fixed.

**Comment by alishiarin** [comment]
Got it, it’s now fixed, thank you so so much!

Thanks again and take care!
