### ISSUE TITLE
Breaking change last update of the addon

### ISSUE THREAD

**Issue by Karakaz** [getov/CharacterStatsClassic#68]
![classic_stats_issue](https://user-images.githubusercontent.com/5980958/117547515-3f309780-b030-11eb-9e96-127b127544ca.png)

Seems like default stats are always being shown underneath.

Version 1.13.7.38475 of the game.

**Comment by getov** [comment]
Make sure to also download the latest alpha of Leatrix Plus - https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
There was an incompatibility issue which is now fixed.
