### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by Velarya** [getov/CharacterStatsClassic#69]
![Screenshot 2021-05-08 224148](https://user-images.githubusercontent.com/83885781/117552944-bffe8c00-b04e-11eb-8858-5e7ff0e31ec2.png)

**Comment by getov** [comment]
Make sure to download the latest version of CharacterStatsClassic and the latest alpha of Leatrix Plus (1.13.105) - https://www.curseforge.com/wow/addons/leatrix-plus-classic/files/all
There was an incompatibility issue which is now fixed.
