### ISSUE TITLE
Says I'm over-capped on defence but that's not true...

### ISSUE THREAD

**Issue by LandonStewart** [getov/CharacterStatsClassic#73]
<img width="657" alt="Screen Shot 2021-12-02 at 10 15 01 PM" src="https://user-images.githubusercontent.com/2685312/144673664-5278f6a4-b114-49e6-b276-ff77842ce945.png">

Is the add-on telling me lies?

REFERENCE: 
https://forums.askmrrobot.com/t/prot-paladin-is-this-ok-over-capped-on-defense/12768

**Comment by getov** [comment]
No, it is not telling lies. You have 77 resilience which is roughly equivalent to "154 def" therefore helping you with your crit immunity. You might want to read up on how resilience impacts crit cap.
