### ISSUE TITLE
Era: (Mage): GetSpellHitModifier() returns hitrate instead of %

### ISSUE THREAD

**Issue by Laumesis** [getov/CharacterStatsClassic#74]
On WoW Classic Era (I guess also SoM) `GetSpellHitModifier()` return should be divided by 7 to get hit% from gear. I tested only on Mage.

Client v1.14.1.41511

**Comment by getov** [comment]
Thanks for the input! So it looks like it's similar to TBC.
I've fixed there with a custom solution. I don't have a character to test it with in Classic Era. Can commit a blind fix.
